version: '3.9'

services:
  api-account-microservice:
    container_name: AccountMicroservice
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    command: uvicorn app.api.AccountMicroservice.main:app --host 0.0.0.0 --port 8001
    env_file:
      - .env
    ports:
      - 8081:8001


  api-hospitals-microservice:
    container_name: HospitalMicroservice
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    command: uvicorn app.api.HospitalMicroservice.main:app --host 0.0.0.0 --port 8002
    env_file:
      - .env
    ports:
      - 8082:8002


  api-timetable-microservice:
    container_name: TimetableMicroservice
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    command: uvicorn app.api.TimetableMicroservice.main:app --host 0.0.0.0 --port 8003
    env_file:
      - .env
    ports:
      - 8083:8003


  api-document-microservice:
    container_name: DocumentMicroservice
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    command: uvicorn app.api.DocumentMicroservice.main:app --host 0.0.0.0 --port 8004
    env_file:
      - .env
    ports:
      - 8084:8004


  db:
    image: postgres:13.8-bullseye
    container_name: simbir-health-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - sh_db:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  sh_db:
    name: sh_db